#!/usr/bin/env python3
"""Tests for the setup-keel-tools installer, with a fixture Keel repository and a fake cargo (no network, no build)."""

from __future__ import annotations

import os
import pathlib
import subprocess
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
ACTION = ROOT / ".github" / "actions" / "setup-keel-tools"
INSTALLER = ACTION / "install-keel-tools.sh"
GIT_ENV = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
           "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com"}

# A fake cargo: `cargo install <crate|--path P> [--version V] --locked --root DIR` writes a stub binary
# into DIR/bin and appends the call to $CARGO_LOG, so a test can see whether anything was built.
FAKE_CARGO = r"""#!/usr/bin/env bash
set -euo pipefail
echo "$*" >> "$CARGO_LOG"
root=""; version=""; path=""; crate=""
shift  # install
while [ $# -gt 0 ]; do
  case "$1" in
    --root) root="$2"; shift 2 ;;
    --version) version="$2"; shift 2 ;;
    --path) path="$2"; shift 2 ;;
    --locked) shift ;;
    *) crate="$1"; shift ;;
  esac
done
mkdir -p "$root/bin"
if [ "$crate" = wasm-bindgen-cli ]; then
  printf '#!/bin/sh\necho "wasm-bindgen %s"\n' "$version" > "$root/bin/wasm-bindgen"
  chmod +x "$root/bin/wasm-bindgen"
else
  test -f "$path/Cargo.toml"
  printf '#!/bin/sh\necho keel\n' > "$root/bin/keel"
  chmod +x "$root/bin/keel"
fi
"""

LOCK = """# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "wasm-bindgen"
version = "0.2.93"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "wasm-bindgen-backend"
version = "0.2.93"
"""


def git(cwd, *args):
    return subprocess.run(["git", *args], cwd=cwd, env={**os.environ, **GIT_ENV}, check=True,
                          text=True, capture_output=True).stdout.strip()


class InstallerTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        base = pathlib.Path(self.tmp.name)
        keel = base / "keel-work"
        (keel / "crates" / "keel-cli").mkdir(parents=True)
        (keel / "crates" / "keel-cli" / "Cargo.toml").write_text("[package]\nname = \"keel-cli\"\n")
        git(keel, "init", "-q", "-b", "main")
        git(keel, "add", "-A")
        git(keel, "commit", "-q", "-m", "c1")
        self.pin = git(keel, "rev-parse", "HEAD")
        self.keel_repo = base / "keel.git"
        git(base, "clone", "-q", "--bare", str(keel), str(self.keel_repo))
        self.title = base / "title"
        self.title.mkdir()
        (self.title / "KEEL_PIN").write_text(self.pin + "\n")
        (self.title / "Cargo.lock").write_text(LOCK)
        fakebin = base / "fakebin"
        fakebin.mkdir()
        (fakebin / "cargo").write_text(FAKE_CARGO)
        (fakebin / "cargo").chmod(0o755)
        self.cargo_log = base / "cargo.log"
        self.github_path = base / "github_path"
        self.root = base / "runner" / "keel-tools"
        (base / "runner").mkdir()
        self.env = {**os.environ, **GIT_ENV, "PATH": f"{fakebin}:{os.environ['PATH']}",
                    "CARGO_LOG": str(self.cargo_log), "KEEL_REPO": str(self.keel_repo),
                    "RUNNER_TEMP": str(base / "runner"), "GITHUB_PATH": str(self.github_path)}
        for k in ("KEEL_PIN", "KEEL_PIN_FILE", "WASM_BINDGEN", "CARGO_LOCK", "KEEL_SRC", "KEEL_FEATURES"):
            self.env.pop(k, None)

    def tearDown(self):
        self.tmp.cleanup()

    def run_installer(self, *args, **env):
        return subprocess.run(["bash", str(INSTALLER), *args], cwd=self.title, env={**self.env, **env},
                              text=True, capture_output=True)

    def builds(self):
        return self.cargo_log.read_text().splitlines() if self.cargo_log.exists() else []

    def test_key_names_pin_and_bindgen(self):
        r = self.run_installer("key")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.strip(), f"keel-{self.pin}-wasm-bindgen-0.2.93")
        r = self.run_installer("key", WASM_BINDGEN="none")
        self.assertEqual(r.stdout.strip(), f"keel-{self.pin}-wasm-bindgen-none")

    def test_key_carries_the_features(self):
        # Two shapes of one pin are two cache entries: without this, a warm key
        # from the other shape restores a root whose stamp differs, rebuilds,
        # and the save step is skipped (cache-hit is true), so it never warms.
        plain = self.run_installer("key")
        self.assertEqual(plain.returncode, 0, plain.stderr)
        r = self.run_installer("key", KEEL_FEATURES="texture-encoder")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.strip(), plain.stdout.strip() + " features=texture-encoder")
        # Spaces and commas name the same shape, so they are the same entry; a
        # comma would split the key's parts.
        self.assertEqual(self.run_installer("key", KEEL_FEATURES=" texture-encoder ").stdout.strip(),
                         r.stdout.strip())
        self.assertEqual(self.run_installer("key", KEEL_FEATURES="texture-encoder,foo").stdout.strip(),
                         plain.stdout.strip() + " features=texture-encoder foo")
        self.assertNotIn(",", r.stdout)

    def test_cold_builds_then_warm_is_from_cache(self):
        r = self.run_installer("install", str(self.root))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("building keel tools", r.stdout)
        self.assertEqual(len(self.builds()), 2)
        self.assertEqual((self.root / "stamp").read_text(), f"keel={self.pin} wasm-bindgen=0.2.93")
        self.assertIn(f"{self.root}/bin", self.github_path.read_text())
        # The second run is the warm cache: same root, nothing built.
        r = self.run_installer("install", str(self.root))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn(f"keel tools from cache: keel={self.pin} wasm-bindgen=0.2.93", r.stdout)
        self.assertEqual(len(self.builds()), 2)

    def test_a_new_bindgen_version_rebuilds(self):
        self.assertEqual(self.run_installer("install", str(self.root)).returncode, 0)
        (self.title / "Cargo.lock").write_text(LOCK.replace("0.2.93", "0.2.95"))
        r = self.run_installer("install", str(self.root))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("building keel tools", r.stdout)
        self.assertEqual(len(self.builds()), 4)

    def test_half_built_root_without_stamp_rebuilds(self):
        (self.root / "bin").mkdir(parents=True)
        r = self.run_installer("install", str(self.root))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("building keel tools", r.stdout)

    def test_wasm_bindgen_none_builds_only_keel(self):
        (self.title / "Cargo.lock").unlink()
        r = self.run_installer("install", str(self.root), WASM_BINDGEN="none")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(len(self.builds()), 1)
        self.assertFalse((self.root / "bin" / "wasm-bindgen").exists())

    def test_existing_keel_src_is_used_and_checked(self):
        src = pathlib.Path(self.tmp.name) / "SylphxAI" / "keel"
        git(self.tmp.name, "clone", "-q", str(self.keel_repo), str(src))
        r = self.run_installer("install", str(self.root), KEEL_SRC=str(src), KEEL_REPO="/nonexistent")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn(f"--path {src}/crates/keel-cli", self.builds()[-1])

    def test_explicit_pin_overrides_file(self):
        (self.title / "KEEL_PIN").unlink()
        r = self.run_installer("key", KEEL_PIN=self.pin)
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_features_are_passed_and_stamped(self):
        r = self.run_installer("install", str(self.root), KEEL_FEATURES="texture-encoder")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertTrue(self.builds()[-1].endswith("--features texture-encoder"), self.builds()[-1])
        self.assertIn("features=texture-encoder", (self.root / "stamp").read_text())
        built = len(self.builds())
        # The same features are the warm cache; other features are another entry.
        self.assertIn("keel tools from cache", self.run_installer("install", str(self.root),
                                                                  KEEL_FEATURES=" texture-encoder ").stdout)
        self.assertEqual(len(self.builds()), built)
        r = self.run_installer("install", str(self.root), KEEL_FEATURES="texture-encoder,foo")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("building keel tools", r.stdout)
        self.assertTrue(self.builds()[-1].endswith("--features texture-encoder foo"), self.builds()[-1])

    def test_rejects_short_pin_and_missing_bindgen(self):
        (self.title / "KEEL_PIN").write_text("abc123\n")
        r = self.run_installer("key")
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("not a full commit sha", r.stderr)
        (self.title / "KEEL_PIN").write_text(self.pin)
        (self.title / "Cargo.lock").write_text("version = 3\n")
        r = self.run_installer("key")
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("no wasm-bindgen crate", r.stderr)


if __name__ == "__main__":
    unittest.main()
